version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-backend:${BACKEND_VERSION}
    container_name: sausage-backend
    environment:
      SPRING_DATASOURCE_USERNAME: ${PSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${PSQL_PASSWORD}
      SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27018/${MONGO_DATABASE}?tls=true
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    restart: always
    networks:
      - sausage-store

  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-backend-report:${BACKEND_REPORT_VERSION}
    container_name: sausage-backend-report
    restart: always
    environment:
      PORT: 8080
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27018/${MONGO_DATABASE}?tls=true
    networks:
      - sausage-store

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-frontend:${FRONTEND_VERSION}
    container_name: sausage-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store: